name: reecespectbrand
favicon: null
layout_spectrum: 1
typography_spectrum: 0.50154
title: Reece Spect Brand
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fba300'
    - '#103642'
    - '#8f7823'
    - '#ffffff'
    - '#a4b3b7'
  brandStrength: 1
  lightness: 0.5868942872621119
  saturation: 0.3125
  rhythmicContrast: 0.5563732844311744
purpose: []
